name: Test

on:
  pull_request:
    branches: [develop, main]

permissions:
  pull-requests: write
  issues: write

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci
      - name: Run extension tests
        run: xvfb-run -a npm test